fix(ipnewton): zeros() instead of undef allocation
JuliaNLSolvers/Optim.jl pull request #973
Opened 2022-02-02 14:12 UTC by gwater

Prevent non-deterministic behavior in interior point Newton method

Ref: #971

2022-02-02 14:19 UTC, johnmyleswhite commented
LGTM, but others should approve

2022-02-04 09:16 UTC, pkofod commented
Thanks, but let me just see the original issue. I think the appropriate thing here is to fill with NaNs because we expect users to take responsibility of all elements of the partial derivatives. You are right that this may be something we should emphasize more in the docs, but I only skimmed the issue, let me read it in detail.

2022-02-04 09:36 UTC, pkofod requested changes

2022-02-04 09:36 UTC, pkofod commented on src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
> +    constr_c = zeros(T, mc)
I would prefer this to be `fill(T(NaN), mc)`. The reason is that the user would immediately realize if they forgot to set all the elements they want to set. If it starts as zero, you might not realize that you're not setting element number 4 ever, because the 0 will not ruin the calculations.

2022-02-04 09:36 UTC, pkofod commented on src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
> +    H = zeros(T, n, n)
Same here

2022-02-04 13:06 UTC, gwater commented on src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
> +    H = zeros(T, n, n)
ok, i think the best solution here is to use `collect` for H rather than splitting allocation and initialization.

2022-02-04 13:06 UTC, gwater commented on src/multivariate/solvers/constrained/ipnewton/ipnewton.jl
> +    constr_c = zeros(T, mc)
agreed

2022-02-04 16:06 UTC, gwater commented
It looks like this test problem does not fill all components of the constraint Jacobian https://github.com/JuliaNLSolvers/OptimTestProblems.jl/blob/45650b6fbbfb07892f827dd74aee03f5e32afc20/src/optim_tests/multivariate/constrained.jl#L81

2022-02-07 09:47 UTC, gwater commented
Basically, all tests fail now because the test case actually leaves some fields of the Jacobian buffer unset. I've opened a PR to fix the test case https://github.com/JuliaNLSolvers/OptimTestProblems.jl/pull/20

2022-02-17 16:12 UTC, gwater commented
as far as i can tell, its still checking with the old test cases

2022-02-28 19:22 UTC, pkofod commented
Thanks!

2022-02-28 19:22 UTC, merged